"""Add start_date and finish_date columns

Revision ID: 66a6a76fa8dc
Revises: d7438dfa9ad5
Create Date: 2025-08-27 08:51:13.394560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a6a76fa8dc'
down_revision = 'd7438dfa9ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('finish_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('finish_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
